notifications:
    email: false

language: objective-c

before_install:
    - brew update &>brew-update.log
    - brew install gradle &>brew-gradle.log
    - brew install adobe-air-sdk &>brew-adobe-air-sdk.log
    
script:
    - gradle build
    
after_failure:
    - tail brew-adobe-air-sdk.log

after_script:
    - ls